"""user in public schema

Revision ID: 6e77ef5b382d
Revises: 0d3366dc4316
Create Date: 2025-07-25 15:13:36.668614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e77ef5b382d'
down_revision: Union[str, Sequence[str], None] = '0d3366dc4316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_tenant_association_user_id_fkey'), 'user_tenant_association', type_='foreignkey')
    op.drop_constraint(op.f('user_tenant_association_tenant_id_fkey'), 'user_tenant_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_tenant_association', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_tenant_association', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_name'), 'users', ['name'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_name'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'user_tenant_association', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_tenant_association', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_tenant_association_tenant_id_fkey'), 'user_tenant_association', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('user_tenant_association_user_id_fkey'), 'user_tenant_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
